### ISSUE TITLE
stream deck pangolin beyond laser 

### ISSUE THREAD

**Issue by Laseryann** [bitfocus/companion-module-pangolin-beyond#2]
hello little question someone is using a stream deck on beyond for quick shortcuts very practical as a device, I believe that pangolin does not work with

**Comment by Laseryann** [comment]
hello I made a little video to show you the problem, I'm sorry I spoke badly I use a translator I'm in France thank you for your understanding
https://youtu.be/lOUL2CsdRtY

**Comment by JeffreyDavidsz** [comment]
You are using the streamdeck app, that's not companion. For Companion to work remove the app or use a plug-in and install Companion. I'll close this issue now
